/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package covas.supermegatraining;

import at.favre.lib.crypto.bcrypt.BCrypt;
import covas.dataaccess.DataAccess;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import covas.supermegatraining.MainJPanel;
import java.awt.Label;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Toni Covas
 */
public class Main extends javax.swing.JFrame {

    public String getUsuariSeleccionatTexte() {
        return usuariSeleccionatTexte;
    }

    public void setUsuariSeleccionatTexte(String usuariSeleccionatTexte) {
        this.usuariSeleccionatTexte = usuariSeleccionatTexte;
    }



    private Usuari usuariActiu=null;
    private DataAccess da= new DataAccess();
    private Usuari usuariSeleccionat=null;
    private String usuariSeleccionatTexte="";
    private DefaultTableModel model;
    private MainJPanel pnlMain;
    private VistaUsuaris pnlVistaUsuaris;
    private VistaWorkouts pnlVistaWorkouts;
    private LogIn pnlLogIn;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        
    
        
 
        
        jPanel3.setLocation(getWidth()-300, 20);   // panell amb el nom d'usuari actiu visible y botó de Log Out
        
        pnlMain=new MainJPanel(this);
        pnlMain.setBounds(1,35,getContentPane().getWidth(),280);
        pnlMain.setSize(getContentPane().getWidth(),280);
        //pnlMain.setSize(getContentPane().getSize());
        //getContentPane().removeAll();
        getContentPane().add(pnlMain);
        repaint();
        
        
 

        
        
        
        
        
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonLogOut = new javax.swing.JButton();
        jLabelUsuariRegistrat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReadUsuaris = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaShowInfoUsuaris = new javax.swing.JTextArea();
        jTableWorkOutsperborrar = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jPanel3.setVisible(false);
        jPanel3.setLayout(null);

        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLogOut);
        jButtonLogOut.setBounds(155, 15, 73, 23);

        jLabelUsuariRegistrat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuariRegistrat.setText("Usuari:");
        jLabelUsuariRegistrat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabelUsuariRegistrat);
        jLabelUsuariRegistrat.setBounds(6, 14, 143, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(430, 0, 252, 50);

        jPanel1.setVisible(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jPanel1.setLayout(null);

        btnReadUsuaris.setText("Veure els meus clients");
        btnReadUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadUsuarisActionPerformed(evt);
            }
        });
        jPanel1.add(btnReadUsuaris);
        btnReadUsuaris.setBounds(5, 18, 146, 23);

        txaShowInfoUsuaris.setColumns(20);
        txaShowInfoUsuaris.setRows(5);
        jScrollPane1.setViewportView(txaShowInfoUsuaris);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(5, 53, 234, 119);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 360, 244, 183);

        jTableWorkOutsperborrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "blanc", "ForDate", "IdWorkout"
            }
        ));
        getContentPane().add(jTableWorkOutsperborrar);
        jTableWorkOutsperborrar.setBounds(0, 0, 150, 0);
        if (jTableWorkOutsperborrar.getColumnModel().getColumnCount() > 0) {
            jTableWorkOutsperborrar.getColumnModel().getColumn(0).setMinWidth(0);
            jTableWorkOutsperborrar.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableWorkOutsperborrar.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jMenu1.setText("File");
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu1KeyPressed(evt);
            }
        });

        jMenuItem1.setText("Sortir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUsuariActiu(Usuari usuariActiu) {
        this.usuariActiu = usuariActiu;
    }


    public Usuari getUsuariActiu() {
        return usuariActiu;
    }
    
    public Usuari getUsuariSeleccionat() {
        return usuariSeleccionat;
    }
    

    public void  setUsuariSeleccionat(Usuari usuari) {
        this.usuariSeleccionat=usuari;
    }

    
    
    public void abrirLogin() {
        pnlLogIn=new LogIn(this, true);
        //pnlLogIn.setBounds(1,10,20,20);
        //pnlLogIn.setSize(350,200);
        //pnlLogIn.setSize(main.getSize());
        pnlLogIn.setVisible(true);
        
        
        
        //getContentPane().removeAll();
        //getContentPane().add(pnlLogIn);
        //repaint();
        
        
    }
    
    
    
    private void btnReadUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadUsuarisActionPerformed



        DataAccess da = new DataAccess();
        ArrayList<Usuari> usuaris = da.getAllUsersByInstructor(getUsuariActiu().getId() );
        txaShowInfoUsuaris.removeAll();
        for(Usuari u: usuaris)  {
            txaShowInfoUsuaris.append(u.getId() + " " + u.getNom()  + "\n");

        }

        
    }//GEN-LAST:event_btnReadUsuarisActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
                
                jLabelUsuariRegistrat.setText("");
                jPanel3.setVisible(false);        // TODO add your handling code here:
                jPanel1.setVisible(false);
                
                
                
               
                
                JOptionPane.showMessageDialog(this, "Hasta Luego " + jLabelUsuariRegistrat.getText() +  " !.  Su sesión ha sido desconectada");              
                setUsuariActiu(null);
                getContentPane().remove(pnlVistaUsuaris);
                getContentPane().remove(pnlVistaWorkouts);
                pnlMain.getJLabelSignIn().setVisible(true);
                repaint();
                
                
                
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0)   ;     // TODO add your handling code here:;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
      
    
    
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //JOptionPane.showMessageDialog(jMenuItem2, "Aplicació creada per Toni Covas Nicolau\nVersión 1.0\n\nGrau Superior DAM - Desenvolupament aplicaciones multiplataforma\nMòdul: Desenvolupament d'interfícies \nCIFP Pau Casesnoves", "Acerca de", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
        final JOptionPane pane = new JOptionPane("Aplicació creada per Toni Covas Nicolau\nVersión 1.0\n\nGrau Superior DAM - Desenvolupament aplicaciones multiplataforma\nMòdul: Desenvolupament d'interfícies \nCIFP Pau Casesnoves" );
        final JDialog d = pane.createDialog((JFrame)null, "About...");
        d.setLocation(jMenuItem2.getLocation().x+5, jMenuItem2.getLocation().y+2    );
        d.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu1KeyPressed
    
    }//GEN-LAST:event_jMenu1KeyPressed

    /**
     * @param args the command line arguments
     */
    
    public void registrarUsuariActiu(Usuari usuari) {
        pnlMain.getJLabelSignIn().setVisible(false);
        this.usuariActiu=usuari;
        jLabelUsuariRegistrat.setText("Usuari: " + this.usuariActiu.getNom());                 
        jLabelUsuariRegistrat.setVisible(true);
        jPanel3.setVisible(true);
    }
    
    public  void carregarLlistaUsuarisInstructor() {
        if (pnlVistaWorkouts!=null) {getContentPane().remove(pnlVistaWorkouts);}
        DefaultListModel llistaBase = new DefaultListModel();
        ArrayList<Usuari> usuaris = da.getAllUsersByInstructor(getUsuariActiu().getId() );
//Recorrer el contenido del ArrayList
            for(int i=0; i<usuaris.size(); i++) {
    //Añadir cada elemento del ArrayList en el modelo de la lista
            llistaBase.add(i, usuaris.get(i).getNom());
}
//Asociar el modelo de lista al JList
    
        
        pnlVistaUsuaris = new VistaUsuaris(this);
        pnlVistaUsuaris.setBounds(1,320,getContentPane().getWidth(),500);
        pnlVistaUsuaris.setSize(getContentPane().getWidth(),300);
            pnlVistaUsuaris.getListUsuarisInstructor().setModel(llistaBase);
        
        
            getContentPane().add(pnlVistaUsuaris);
                
        repaint();

        
        
        
                
    
        
    }
    
    
    public  void carregarLlistaWorkOutsUsuari(String nomUsuari) {
         setUsuariSeleccionatTexte(nomUsuari)        ;
        pnlVistaWorkouts = new VistaWorkouts(this);
        pnlVistaWorkouts.setBounds(1,320,getContentPane().getWidth(),500);
        pnlVistaWorkouts.setSize(getContentPane().getWidth(),300);
            
        
        getContentPane().remove(pnlVistaUsuaris);
            getContentPane().add(pnlVistaWorkouts);
            
                
        repaint();

            
        
            
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadUsuaris;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabelUsuariRegistrat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWorkOutsperborrar;
    private javax.swing.JTextArea txaShowInfoUsuaris;
    // End of variables declaration//GEN-END:variables
}
